name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  smooth_page_indicator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/background1.png
    - assets/images/background2.png
    - assets/images/background3.png
    - assets/images/background4.png
    - assets/images/next.png
    - assets/images/getstarted.png
    - assets/images/Component15.png
    - assets/images/loginbouton.png

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora/static/Lora-Bold.ttf # Remplacez le chemin par l'emplacement de votre fichier de police
        - asset: assets/fonts/Lora/static/Lora-Medium.ttf    # Si vous avez une version en gras de la police
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/Montserrat/static/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Medium.ttf

  uses-material-design: true
